
export enum EntityCategory {
  PERSON = 'person',           // Individuals, Key Figures
  ORGANIZATION = 'org',        // Groups, Companies, Parties, Families
  TECHNOLOGY = 'tech',         // Tools, Machines, Software, Infrastructure
  RESOURCE = 'resource',       // Natural resources, Money, Capital
  BELIEF = 'belief',           // Ideologies, Religions, Laws, Customs
  EVENT = 'event',             // Historical moments (Time dimension)
  PLACE = 'place',             // Locations, Environments
  UNKNOWN = 'unknown'
}

export interface SocialEntity {
  id: string;
  name: string;
  description: string;
  category: EntityCategory;
  validFrom?: string; // Start of existence (e.g. "1900", "Chapter 1")
  validTo?: string;   // End of existence (e.g. "2000", "Chapter 5")
}

export interface EntityState {
  id: string;
  entityId: string;
  timestamp: string; // e.g. "2020", "Phase 1"
  description: string;
}

export interface EntityRelationship {
  id: string;
  sourceId: string;
  targetId: string;
  type: string; // e.g. "Friend", "Enemy", "Subordinate", "Owner"
  description?: string;
  timestamp?: string; // Specific moment snapshot
  validFrom?: string; // Relationship start
  validTo?: string;   // Relationship end
}

// --- Tech Tree Types ---

export interface TechNode {
  id: string;
  name: string;
  description: string;
  era: string; // e.g. "Industrial Age", "2020s", "Age of Fire"
  type: 'military' | 'civil' | 'abstract';
  status: 'concept' | 'prototype' | 'production' | 'obsolete';
  x?: number; // Persisted Layout X
  y?: number; // Persisted Layout Y
}

export interface TechDependency {
  id: string;
  sourceId: string; // Prerequisite
  targetId: string; // Result
}

// --- Agent & Workflow Types ---

export type ArtifactType = 'text' | 'markdown' | 'code' | 'json';

export interface StoryArtifact {
  id: string;
  title: string;
  type: ArtifactType;
  content: string;
  sourceStepId?: string; // If generated by a step
  createdAt: number;
}

export interface StoryAgent {
  id: string;
  name: string;
  role: string; // e.g. "Historian", "Novelist", "Critic"
  systemPrompt: string; // The persona definition
  color: string; // UI decoration
  icon: string; // UI decoration
}

export interface StepValidation {
  reviewerId: string;
  criteria: string;
  maxRetries: number;
}

export interface WorkflowStep {
  id: string;
  name: string;
  agentId: string;
  instruction: string; // Specific task for this step
  outputContext?: string; // Holds the result after execution
  outputArtifactType?: ArtifactType; // Configures what kind of artifact this step produces
  validation?: StepValidation; // Optional iterative review config
}

// The WorldModel is now a flat pool of entities and relationships
export interface WorldModel {
  entities: SocialEntity[];
  relationships: EntityRelationship[];
  entityStates: EntityState[];

  // Tech Tree
  technologies: TechNode[];
  techDependencies: TechDependency[];
}

export interface LayerDefinition {
  id: string;
  title: string;
  description: string;
  colorClass: string;
  isTimeDimension?: boolean;
  // Which categories of entities belong to this layer in this framework?
  allowedCategories: EntityCategory[];
}

export interface FrameworkDefinition {
  id: string;
  name: string;
  description: string;
  layers: LayerDefinition[];
}

export interface StorySegment {
  id: string;
  timestamp: string;
  content: string;
  influencedBy: string[]; // Entity IDs
}

export interface WorldData {
  id?: string;
  name: string;
  frameworkId: string;
  createdAt: number;
  lastModified: number;
  context: string;
  model: WorldModel; // Flat model
  storySegments: StorySegment[];
  currentTimeSetting: string;
  chronicleText?: string;

  // Agent System Data
  agents: StoryAgent[];
  workflow: WorkflowStep[];
  artifacts?: StoryArtifact[]; // Optional for backward compatibility with old saves
}

export type ApiProvider = 'google' | 'openai';

export interface ApiSettings {
  provider: ApiProvider;
  apiKey: string;
  baseUrl: string;
  model: string;
  minimalUI?: boolean;
}

// --- Brainstorm Types ---

export interface BrainstormMessage {
  id: string;
  role: 'user' | 'model';
  content: string;
  timestamp: number;
}

export interface BrainstormConfig {
  provider: ApiProvider;
  apiKey: string;
  baseUrl: string;
  model: string;
  temperature: number;
  maxOutputTokens?: number;
  systemInstruction?: string;
}

export interface BrainstormSession {
  id: string;
  name: string;
  messages: BrainstormMessage[];
  config: BrainstormConfig;
  createdAt: number;
  lastModified: number;
}

export interface StepExecutionLog {
  status: 'pending' | 'generating' | 'reviewing' | 'revising' | 'completed' | 'failed';
  content: string;
  attempts: {
    round: number;
    output: string;
    critique?: string;
    verdict?: 'PASS' | 'FAIL';
  }[];
  error?: string;
}

// --- Git Types ---

export interface GitChange {
  status: string;
  path: string;
}

export interface GitLog {
  hash: string;
  author: string;
  message: string;
  date: string;
}