import { Octokit } from 'octokit';

interface FileCommit {
    path: string;
    content: string; // Base64 encoded or string
    message: string;
    branch?: string;
}

export class GitHubService {
    private octokit: Octokit;
    private owner: string;
    private repo: string;
    private user: any = null;

    constructor(octokit: Octokit) {
        this.octokit = octokit;
        this.owner = ""; // To be set after fetching user or passed in
        this.repo = ""; // Set by context/user selection
    }

    async initialize() {
        if (!this.user) {
            const { data } = await this.octokit.rest.users.getAuthenticated();
            this.user = data;
            this.owner = data.login;
        }
    }

    async ensureRepoExists() {
        await this.initialize();
        try {
            await this.octokit.rest.repos.get({
                owner: this.owner,
                repo: this.repo,
            });
        } catch (e: any) {
            if (e.status === 404) {
                // Create repo
                await this.octokit.rest.repos.createForAuthenticatedUser({
                    name: this.repo,
                    description: "Stories and Worlds generated by EcoNarrative Studio",
                    private: true,
                    auto_init: true, // Create Initial Commit with README
                });
            } else {
                throw e;
            }
        }
    }

    async saveFile({ path, content, message, branch }: FileCommit) {
        await this.ensureRepoExists();

        let sha: string | undefined;
        try {
            const { data } = await this.octokit.rest.repos.getContent({
                owner: this.owner,
                repo: this.repo,
                path,
                ref: branch,
            });
            if (!Array.isArray(data)) { // It's a file
                sha = data.sha;
            }
        } catch (e: any) {
            // File doesn't exist, create new
            if (e.status !== 404) throw e;
        }

        const encodedContent = btoa(unescape(encodeURIComponent(content))); // Handle UTF-8 strings

        await this.octokit.rest.repos.createOrUpdateFileContents({
            owner: this.owner,
            repo: this.repo,
            path,
            message,
            content: encodedContent,
            sha,
            branch,
        });
    }

    async createBranch(branchName: string, sourceBranch: string = 'main') {
        await this.ensureRepoExists();

        // Get SHA of source branch head
        const { data: refData } = await this.octokit.rest.git.getRef({
            owner: this.owner,
            repo: this.repo,
            ref: `heads/${sourceBranch}`,
        });

        const sha = refData.object.sha;

        await this.octokit.rest.git.createRef({
            owner: this.owner,
            repo: this.repo,
            ref: `refs/heads/${branchName}`,
            sha,
        });
    }

    async listBranches() {
        await this.ensureRepoExists();
        const { data } = await this.octokit.rest.repos.listBranches({
            owner: this.owner,
            repo: this.repo,
        });
        return data;
    }
    setRepo(repoName: string) {
        this.repo = repoName;
    }

    getRepo() {
        return this.repo;
    }

    async listRepos() {
        if (!this.user) await this.initialize();
        const { data } = await this.octokit.rest.repos.listForAuthenticatedUser({
            sort: 'updated',
            direction: 'desc',
            per_page: 100
        });
        return data;
    }

    async createRepo(name: string, description: string = "Created by EcoNarrative Studio") {
        const { data } = await this.octokit.rest.repos.createForAuthenticatedUser({
            name,
            description,
            private: true,
            auto_init: true,
        });
        this.repo = name;
        return data;
    }
}
