import React, { useState, useEffect } from 'react';
import { Github, Plus, Search, Book, Check, Loader2, RefreshCw } from 'lucide-react';
import { useGitHub } from './GitHubContext';

interface RepoSelectionModalProps {
    isOpen: boolean;
    onClose: () => void;
}

export const RepoSelectionModal: React.FC<RepoSelectionModalProps> = ({ isOpen, onClose }) => {
    const { user, listRepos, createRepo, selectRepo, currentRepo } = useGitHub();
    const [repos, setRepos] = useState<any[]>([]);
    const [isLoading, setIsLoading] = useState(false);
    const [searchTerm, setSearchTerm] = useState("");
    const [activeTab, setActiveTab] = useState<'existing' | 'new'>('existing');

    // New Repo Form
    const [newRepoName, setNewRepoName] = useState("my-eco-stories");
    const [newRepoDesc, setNewRepoDesc] = useState("Stories generated by EcoNarrative Studio");
    const [isCreating, setIsCreating] = useState(false);

    useEffect(() => {
        if (isOpen && activeTab === 'existing') {
            loadRepos();
        }
    }, [isOpen, activeTab]);

    const loadRepos = async () => {
        setIsLoading(true);
        try {
            const data = await listRepos();
            setRepos(data);
        } catch (error) {
            console.error("Failed to load repos", error);
        } finally {
            setIsLoading(false);
        }
    };

    const handleSelect = (repoName: string) => {
        selectRepo(repoName);
        onClose();
    };

    const handleCreate = async () => {
        if (!newRepoName) return;
        setIsCreating(true);
        try {
            await createRepo(newRepoName, newRepoDesc);
            onClose();
        } catch (error) {
            console.error("Failed to create repo", error);
            alert("Create failed. Check console.");
        } finally {
            setIsCreating(false);
        }
    };

    if (!isOpen) return null;

    const filteredRepos = repos.filter(r => r.name.toLowerCase().includes(searchTerm.toLowerCase()));

    return (
        <div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/70 backdrop-blur-sm p-4 animate-fadeIn">
            <div className="bg-white rounded-xl shadow-2xl w-full max-w-lg overflow-hidden flex flex-col max-h-[80vh]">

                {/* Header */}
                <div className="p-6 border-b border-slate-100 bg-slate-50 flex items-center justify-between shrink-0">
                    <div>
                        <h2 className="text-xl font-bold text-slate-800 flex items-center gap-2">
                            <Github className="w-6 h-6" />
                            选择存储仓库
                        </h2>
                        <p className="text-slate-500 text-sm mt-1">
                            请选择一个 GitHub 仓库用于同步世界数据。
                        </p>
                    </div>
                </div>

                {/* Tabs */}
                <div className="flex border-b border-slate-200 shrink-0">
                    <button
                        onClick={() => setActiveTab('existing')}
                        className={`flex-1 py-3 text-sm font-medium transition-colors ${activeTab === 'existing' ? 'text-indigo-600 border-b-2 border-indigo-600 bg-indigo-50/50' : 'text-slate-500 hover:bg-slate-50'}`}
                    >
                        选择现有仓库
                    </button>
                    <button
                        onClick={() => setActiveTab('new')}
                        className={`flex-1 py-3 text-sm font-medium transition-colors ${activeTab === 'new' ? 'text-indigo-600 border-b-2 border-indigo-600 bg-indigo-50/50' : 'text-slate-500 hover:bg-slate-50'}`}
                    >
                        创建新仓库
                    </button>
                </div>

                {/* Content */}
                <div className="flex-1 overflow-y-auto p-0 bg-slate-50/50 relative min-h-[300px]">

                    {activeTab === 'existing' && (
                        <div className="flex flex-col h-full">
                            <div className="p-4 sticky top-0 bg-white/90 backdrop-blur border-b border-slate-100 z-10 space-y-2">
                                <div className="relative">
                                    <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
                                    <input
                                        type="text"
                                        placeholder="搜索仓库..."
                                        value={searchTerm}
                                        onChange={e => setSearchTerm(e.target.value)}
                                        className="w-full pl-9 pr-4 py-2 border border-slate-200 rounded-lg text-sm bg-slate-50 focus:outline-none focus:ring-2 focus:ring-indigo-500/20 focus:border-indigo-500"
                                    />
                                </div>
                                <div className="flex justify-between items-center text-xs text-slate-400 px-1">
                                    <span>找到 {filteredRepos.length} 个仓库</span>
                                    <button onClick={loadRepos} className="flex items-center gap-1 hover:text-indigo-600">
                                        <RefreshCw className={`w-3 h-3 ${isLoading ? 'animate-spin' : ''}`} />
                                        刷新
                                    </button>
                                </div>
                            </div>

                            {isLoading ? (
                                <div className="flex flex-col items-center justify-center flex-1 text-slate-400 gap-2">
                                    <Loader2 className="w-8 h-8 animate-spin text-indigo-500" />
                                    <span className="text-sm">加载仓库列表...</span>
                                </div>
                            ) : filteredRepos.length > 0 ? (
                                <div className="divide-y divide-slate-100">
                                    {filteredRepos.map(repo => (
                                        <button
                                            key={repo.id}
                                            onClick={() => handleSelect(repo.name)}
                                            className="w-full text-left px-6 py-4 hover:bg-white transition-colors flex items-center justify-between group"
                                        >
                                            <div className="flex items-start gap-3">
                                                <div className="mt-1 p-1.5 bg-slate-100 text-slate-500 rounded group-hover:bg-indigo-100 group-hover:text-indigo-600 transition-colors">
                                                    <Book className="w-4 h-4" />
                                                </div>
                                                <div>
                                                    <div className="font-medium text-slate-700 group-hover:text-indigo-600">{repo.name}</div>
                                                    <div className="text-xs text-slate-400 mt-0.5 line-clamp-1">{repo.description || "无描述"}</div>
                                                </div>
                                            </div>
                                            {currentRepo === repo.name && (
                                                <div className="flex items-center gap-1 text-xs font-medium text-green-600 bg-green-50 px-2 py-1 rounded-full">
                                                    <Check className="w-3 h-3" />
                                                    当前使用
                                                </div>
                                            )}
                                        </button>
                                    ))}
                                </div>
                            ) : (
                                <div className="flex flex-col items-center justify-center flex-1 text-slate-400 gap-4 mt-8">
                                    <div className="w-16 h-16 bg-slate-100 rounded-full flex items-center justify-center">
                                        <Search className="w-8 h-8 text-slate-300" />
                                    </div>
                                    <p>未找到匹配的仓库</p>
                                </div>
                            )}
                        </div>
                    )}

                    {activeTab === 'new' && (
                        <div className="p-6 space-y-6">
                            <div className="space-y-2">
                                <label className="block text-sm font-medium text-slate-700">仓库名称</label>
                                <div className="relative">
                                    <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                                        <span className="text-slate-400 text-sm">{user?.login} /</span>
                                    </div>
                                    <input
                                        type="text"
                                        value={newRepoName}
                                        onChange={e => setNewRepoName(e.target.value.replace(/\s+/g, '-'))}
                                        className="w-full pl-[calc(1ch*USER_LOGIN_LENGTH+2rem)] pr-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent font-mono text-sm"
                                        style={{ paddingLeft: `${(user?.login?.length || 0) + 2.5}ch` }}
                                        placeholder="my-awesome-world"
                                    />
                                </div>
                                <p className="text-xs text-slate-500">只能包含字母、数字和连字符。</p>
                            </div>

                            <div className="space-y-2">
                                <label className="block text-sm font-medium text-slate-700">描述 (可选)</label>
                                <textarea
                                    value={newRepoDesc}
                                    onChange={e => setNewRepoDesc(e.target.value)}
                                    rows={3}
                                    className="w-full px-4 py-2 border border-slate-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:border-transparent text-sm resize-none"
                                />
                            </div>

                            <div className="bg-blue-50 text-blue-700 px-4 py-3 rounded-lg text-sm flex items-start gap-2">
                                <div className="mt-0.5"><Book className="w-4 h-4" /></div>
                                <p>新仓库将创建为 <strong>Private (私有)</strong>，并自动初始化 README 文件。</p>
                            </div>

                            <div className="pt-4">
                                <button
                                    onClick={handleCreate}
                                    disabled={isCreating || !newRepoName}
                                    className="w-full py-3 bg-indigo-600 text-white rounded-lg font-bold hover:bg-indigo-700 transition-colors disabled:opacity-50 disabled:cursor-not-allowed flex items-center justify-center gap-2"
                                >
                                    {isCreating ? <Loader2 className="w-5 h-5 animate-spin" /> : <Plus className="w-5 h-5" />}
                                    创建并使用该仓库
                                </button>
                            </div>
                        </div>
                    )}

                </div>
            </div>
        </div>
    );
};
